#### insert
POST /users HTTP/1.1
Host: 127.0.0.1:8087
Content-Type: application/json
Cache-Control: no-cache

{"name":"jack","telephone":"13774403666","ages":20,"lastName":"zhang"}


### get
GET http://127.0.0.1:8087/users/query/dsl2?size=2&page=0&lastName=jac&sort=id,desc&ages=10
Content-Type: application/json
Cache-Control: no-cache

###